name: Build API & Checking

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure code is working as expected
        run: |
          python main.py

      - name: Upload paper-versions.json
        uses: actions/upload-artifact@v4.3.1
        with:
          name: paper-versions.json
          path: paper-versions.json

      - name: Publish code
        id: create_release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: paper-versions.json
          name: "Release v1.${{ github.run_number }}"
          body: "Commit: ${{ github.sha }}\nDownload the `release.zip` file and you are good to go!\nContinue by following the steps given in the README."
          tag_name: ${{ github.ref_name }}

